// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: product.proto

package productpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Product struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductName          string                 `protobuf:"bytes,2,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	CategoryId           int64                  `protobuf:"varint,3,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	CategoryName         string                 `protobuf:"bytes,4,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	ImageUrl             string                 `protobuf:"bytes,5,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	AvailabilityOfPieces int64                  `protobuf:"varint,6,opt,name=availability_of_pieces,json=availabilityOfPieces,proto3" json:"availability_of_pieces,omitempty"`
	Price                float64                `protobuf:"fixed64,7,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{0}
}

func (x *Product) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Product) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *Product) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *Product) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *Product) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Product) GetAvailabilityOfPieces() int64 {
	if x != nil {
		return x.AvailabilityOfPieces
	}
	return 0
}

func (x *Product) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type UpdateProductQuantity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int64                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductQuantity) Reset() {
	*x = UpdateProductQuantity{}
	mi := &file_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductQuantity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductQuantity) ProtoMessage() {}

func (x *UpdateProductQuantity) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductQuantity.ProtoReflect.Descriptor instead.
func (*UpdateProductQuantity) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateProductQuantity) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *UpdateProductQuantity) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int64                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{2}
}

func (x *OrderItem) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *OrderItem) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderItem) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type GetProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductIds    []int64                `protobuf:"varint,1,rep,packed,name=product_ids,json=productIds,proto3" json:"product_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsRequest) Reset() {
	*x = GetProductsRequest{}
	mi := &file_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsRequest) ProtoMessage() {}

func (x *GetProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsRequest.ProtoReflect.Descriptor instead.
func (*GetProductsRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{3}
}

func (x *GetProductsRequest) GetProductIds() []int64 {
	if x != nil {
		return x.ProductIds
	}
	return nil
}

type GetProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsResponse) Reset() {
	*x = GetProductsResponse{}
	mi := &file_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsResponse) ProtoMessage() {}

func (x *GetProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsResponse.ProtoReflect.Descriptor instead.
func (*GetProductsResponse) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{4}
}

func (x *GetProductsResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

type UpdateProductQuantityRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	NewItems      []*UpdateProductQuantity `protobuf:"bytes,1,rep,name=newItems,proto3" json:"newItems,omitempty"`
	OldItems      []*UpdateProductQuantity `protobuf:"bytes,2,rep,name=oldItems,proto3" json:"oldItems,omitempty"`
	IsCreate      bool                     `protobuf:"varint,3,opt,name=isCreate,proto3" json:"isCreate,omitempty"` // Создание заказа
	IsDelete      bool                     `protobuf:"varint,4,opt,name=isDelete,proto3" json:"isDelete,omitempty"` // Отмена заказа
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductQuantityRequest) Reset() {
	*x = UpdateProductQuantityRequest{}
	mi := &file_product_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductQuantityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductQuantityRequest) ProtoMessage() {}

func (x *UpdateProductQuantityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductQuantityRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductQuantityRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateProductQuantityRequest) GetNewItems() []*UpdateProductQuantity {
	if x != nil {
		return x.NewItems
	}
	return nil
}

func (x *UpdateProductQuantityRequest) GetOldItems() []*UpdateProductQuantity {
	if x != nil {
		return x.OldItems
	}
	return nil
}

func (x *UpdateProductQuantityRequest) GetIsCreate() bool {
	if x != nil {
		return x.IsCreate
	}
	return false
}

func (x *UpdateProductQuantityRequest) GetIsDelete() bool {
	if x != nil {
		return x.IsDelete
	}
	return false
}

type UpdateProductQuantityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductQuantityResponse) Reset() {
	*x = UpdateProductQuantityResponse{}
	mi := &file_product_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductQuantityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductQuantityResponse) ProtoMessage() {}

func (x *UpdateProductQuantityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductQuantityResponse.ProtoReflect.Descriptor instead.
func (*UpdateProductQuantityResponse) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateProductQuantityResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateProductQuantityResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type NewProduct struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ProductName          string                 `protobuf:"bytes,1,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	CategoryId           int64                  `protobuf:"varint,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	ImageUrl             string                 `protobuf:"bytes,3,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	AvailabilityOfPieces int64                  `protobuf:"varint,4,opt,name=availability_of_pieces,json=availabilityOfPieces,proto3" json:"availability_of_pieces,omitempty"`
	Price                float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *NewProduct) Reset() {
	*x = NewProduct{}
	mi := &file_product_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewProduct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewProduct) ProtoMessage() {}

func (x *NewProduct) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewProduct.ProtoReflect.Descriptor instead.
func (*NewProduct) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{7}
}

func (x *NewProduct) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *NewProduct) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *NewProduct) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *NewProduct) GetAvailabilityOfPieces() int64 {
	if x != nil {
		return x.AvailabilityOfPieces
	}
	return 0
}

func (x *NewProduct) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type ReturnNewProduct struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductName          string                 `protobuf:"bytes,2,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	CategoryId           int64                  `protobuf:"varint,3,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	ImageUrl             string                 `protobuf:"bytes,4,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	AvailabilityOfPieces int64                  `protobuf:"varint,5,opt,name=availability_of_pieces,json=availabilityOfPieces,proto3" json:"availability_of_pieces,omitempty"`
	Price                float64                `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ReturnNewProduct) Reset() {
	*x = ReturnNewProduct{}
	mi := &file_product_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReturnNewProduct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnNewProduct) ProtoMessage() {}

func (x *ReturnNewProduct) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnNewProduct.ProtoReflect.Descriptor instead.
func (*ReturnNewProduct) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{8}
}

func (x *ReturnNewProduct) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReturnNewProduct) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *ReturnNewProduct) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *ReturnNewProduct) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *ReturnNewProduct) GetAvailabilityOfPieces() int64 {
	if x != nil {
		return x.AvailabilityOfPieces
	}
	return 0
}

func (x *ReturnNewProduct) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type NewCategory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryName  string                 `protobuf:"bytes,2,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewCategory) Reset() {
	*x = NewCategory{}
	mi := &file_product_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewCategory) ProtoMessage() {}

func (x *NewCategory) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewCategory.ProtoReflect.Descriptor instead.
func (*NewCategory) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{9}
}

func (x *NewCategory) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

type ReturnNewCategory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CategoryName  string                 `protobuf:"bytes,2,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReturnNewCategory) Reset() {
	*x = ReturnNewCategory{}
	mi := &file_product_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReturnNewCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnNewCategory) ProtoMessage() {}

func (x *ReturnNewCategory) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnNewCategory.ProtoReflect.Descriptor instead.
func (*ReturnNewCategory) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{10}
}

func (x *ReturnNewCategory) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReturnNewCategory) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

type ProductId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductId) Reset() {
	*x = ProductId{}
	mi := &file_product_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductId) ProtoMessage() {}

func (x *ProductId) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductId.ProtoReflect.Descriptor instead.
func (*ProductId) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{11}
}

func (x *ProductId) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CategoryId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryId) Reset() {
	*x = CategoryId{}
	mi := &file_product_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryId) ProtoMessage() {}

func (x *CategoryId) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryId.ProtoReflect.Descriptor instead.
func (*CategoryId) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{12}
}

func (x *CategoryId) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RemoveMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        bool                   `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMessage) Reset() {
	*x = RemoveMessage{}
	mi := &file_product_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMessage) ProtoMessage() {}

func (x *RemoveMessage) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMessage.ProtoReflect.Descriptor instead.
func (*RemoveMessage) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{13}
}

func (x *RemoveMessage) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RemoveMessage) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *RemoveMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_product_proto protoreflect.FileDescriptor

const file_product_proto_rawDesc = "" +
	"\n" +
	"\rproduct.proto\x12\bproducts\"\xeb\x01\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12!\n" +
	"\fproduct_name\x18\x02 \x01(\tR\vproductName\x12\x1f\n" +
	"\vcategory_id\x18\x03 \x01(\x03R\n" +
	"categoryId\x12#\n" +
	"\rcategory_name\x18\x04 \x01(\tR\fcategoryName\x12\x1b\n" +
	"\timage_url\x18\x05 \x01(\tR\bimageUrl\x124\n" +
	"\x16availability_of_pieces\x18\x06 \x01(\x03R\x14availabilityOfPieces\x12\x14\n" +
	"\x05price\x18\a \x01(\x01R\x05price\"R\n" +
	"\x15UpdateProductQuantity\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x03R\bquantity\"\\\n" +
	"\tOrderItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x03R\bquantity\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\"5\n" +
	"\x12GetProductsRequest\x12\x1f\n" +
	"\vproduct_ids\x18\x01 \x03(\x03R\n" +
	"productIds\"D\n" +
	"\x13GetProductsResponse\x12-\n" +
	"\bproducts\x18\x01 \x03(\v2\x11.products.ProductR\bproducts\"\xd0\x01\n" +
	"\x1cUpdateProductQuantityRequest\x12;\n" +
	"\bnewItems\x18\x01 \x03(\v2\x1f.products.UpdateProductQuantityR\bnewItems\x12;\n" +
	"\boldItems\x18\x02 \x03(\v2\x1f.products.UpdateProductQuantityR\boldItems\x12\x1a\n" +
	"\bisCreate\x18\x03 \x01(\bR\bisCreate\x12\x1a\n" +
	"\bisDelete\x18\x04 \x01(\bR\bisDelete\"S\n" +
	"\x1dUpdateProductQuantityResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xb9\x01\n" +
	"\n" +
	"NewProduct\x12!\n" +
	"\fproduct_name\x18\x01 \x01(\tR\vproductName\x12\x1f\n" +
	"\vcategory_id\x18\x02 \x01(\x03R\n" +
	"categoryId\x12\x1b\n" +
	"\timage_url\x18\x03 \x01(\tR\bimageUrl\x124\n" +
	"\x16availability_of_pieces\x18\x04 \x01(\x03R\x14availabilityOfPieces\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\"\xcf\x01\n" +
	"\x10ReturnNewProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12!\n" +
	"\fproduct_name\x18\x02 \x01(\tR\vproductName\x12\x1f\n" +
	"\vcategory_id\x18\x03 \x01(\x03R\n" +
	"categoryId\x12\x1b\n" +
	"\timage_url\x18\x04 \x01(\tR\bimageUrl\x124\n" +
	"\x16availability_of_pieces\x18\x05 \x01(\x03R\x14availabilityOfPieces\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x01R\x05price\"2\n" +
	"\vNewCategory\x12#\n" +
	"\rcategory_name\x18\x02 \x01(\tR\fcategoryName\"H\n" +
	"\x11ReturnNewCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12#\n" +
	"\rcategory_name\x18\x02 \x01(\tR\fcategoryName\"\x1b\n" +
	"\tProductId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x1c\n" +
	"\n" +
	"CategoryId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"Q\n" +
	"\rRemoveMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\bR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2\xef\x04\n" +
	"\x0fProductsService\x12O\n" +
	"\x10GetProductsByIds\x12\x1c.products.GetProductsRequest\x1a\x1d.products.GetProductsResponse\x12m\n" +
	"\x1aUpdateProductQuantityByIds\x12&.products.UpdateProductQuantityRequest\x1a'.products.UpdateProductQuantityResponse\x12A\n" +
	"\rCreateProduct\x12\x14.products.NewProduct\x1a\x1a.products.ReturnNewProduct\x12D\n" +
	"\x0eCreateCategory\x12\x15.products.NewCategory\x1a\x1b.products.ReturnNewCategory\x12G\n" +
	"\rChangeProduct\x12\x1a.products.ReturnNewProduct\x1a\x1a.products.ReturnNewProduct\x12J\n" +
	"\x0eChangeCategory\x12\x1b.products.ReturnNewCategory\x1a\x1b.products.ReturnNewCategory\x12=\n" +
	"\rRemoveProduct\x12\x13.products.ProductId\x1a\x17.products.RemoveMessage\x12?\n" +
	"\x0eRemoveCategory\x12\x14.products.CategoryId\x1a\x17.products.RemoveMessageBDZBgithub.com/AndreyLebedev1998/shop-gRPC-product/productpb;productpbb\x06proto3"

var (
	file_product_proto_rawDescOnce sync.Once
	file_product_proto_rawDescData []byte
)

func file_product_proto_rawDescGZIP() []byte {
	file_product_proto_rawDescOnce.Do(func() {
		file_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_product_proto_rawDesc), len(file_product_proto_rawDesc)))
	})
	return file_product_proto_rawDescData
}

var file_product_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_product_proto_goTypes = []any{
	(*Product)(nil),                       // 0: products.Product
	(*UpdateProductQuantity)(nil),         // 1: products.UpdateProductQuantity
	(*OrderItem)(nil),                     // 2: products.OrderItem
	(*GetProductsRequest)(nil),            // 3: products.GetProductsRequest
	(*GetProductsResponse)(nil),           // 4: products.GetProductsResponse
	(*UpdateProductQuantityRequest)(nil),  // 5: products.UpdateProductQuantityRequest
	(*UpdateProductQuantityResponse)(nil), // 6: products.UpdateProductQuantityResponse
	(*NewProduct)(nil),                    // 7: products.NewProduct
	(*ReturnNewProduct)(nil),              // 8: products.ReturnNewProduct
	(*NewCategory)(nil),                   // 9: products.NewCategory
	(*ReturnNewCategory)(nil),             // 10: products.ReturnNewCategory
	(*ProductId)(nil),                     // 11: products.ProductId
	(*CategoryId)(nil),                    // 12: products.CategoryId
	(*RemoveMessage)(nil),                 // 13: products.RemoveMessage
}
var file_product_proto_depIdxs = []int32{
	0,  // 0: products.GetProductsResponse.products:type_name -> products.Product
	1,  // 1: products.UpdateProductQuantityRequest.newItems:type_name -> products.UpdateProductQuantity
	1,  // 2: products.UpdateProductQuantityRequest.oldItems:type_name -> products.UpdateProductQuantity
	3,  // 3: products.ProductsService.GetProductsByIds:input_type -> products.GetProductsRequest
	5,  // 4: products.ProductsService.UpdateProductQuantityByIds:input_type -> products.UpdateProductQuantityRequest
	7,  // 5: products.ProductsService.CreateProduct:input_type -> products.NewProduct
	9,  // 6: products.ProductsService.CreateCategory:input_type -> products.NewCategory
	8,  // 7: products.ProductsService.ChangeProduct:input_type -> products.ReturnNewProduct
	10, // 8: products.ProductsService.ChangeCategory:input_type -> products.ReturnNewCategory
	11, // 9: products.ProductsService.RemoveProduct:input_type -> products.ProductId
	12, // 10: products.ProductsService.RemoveCategory:input_type -> products.CategoryId
	4,  // 11: products.ProductsService.GetProductsByIds:output_type -> products.GetProductsResponse
	6,  // 12: products.ProductsService.UpdateProductQuantityByIds:output_type -> products.UpdateProductQuantityResponse
	8,  // 13: products.ProductsService.CreateProduct:output_type -> products.ReturnNewProduct
	10, // 14: products.ProductsService.CreateCategory:output_type -> products.ReturnNewCategory
	8,  // 15: products.ProductsService.ChangeProduct:output_type -> products.ReturnNewProduct
	10, // 16: products.ProductsService.ChangeCategory:output_type -> products.ReturnNewCategory
	13, // 17: products.ProductsService.RemoveProduct:output_type -> products.RemoveMessage
	13, // 18: products.ProductsService.RemoveCategory:output_type -> products.RemoveMessage
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_product_proto_init() }
func file_product_proto_init() {
	if File_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_product_proto_rawDesc), len(file_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_product_proto_goTypes,
		DependencyIndexes: file_product_proto_depIdxs,
		MessageInfos:      file_product_proto_msgTypes,
	}.Build()
	File_product_proto = out.File
	file_product_proto_goTypes = nil
	file_product_proto_depIdxs = nil
}
