// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.20.3
// source: product.proto

package productpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProductsService_GetProductsByIds_FullMethodName           = "/products.ProductsService/GetProductsByIds"
	ProductsService_UpdateProductQuantityByIds_FullMethodName = "/products.ProductsService/UpdateProductQuantityByIds"
	ProductsService_CreateProduct_FullMethodName              = "/products.ProductsService/CreateProduct"
	ProductsService_CreateCategory_FullMethodName             = "/products.ProductsService/CreateCategory"
	ProductsService_ChangeProduct_FullMethodName              = "/products.ProductsService/ChangeProduct"
	ProductsService_ChangeCategory_FullMethodName             = "/products.ProductsService/ChangeCategory"
	ProductsService_RemoveProduct_FullMethodName              = "/products.ProductsService/RemoveProduct"
	ProductsService_RemoveCategory_FullMethodName             = "/products.ProductsService/RemoveCategory"
)

// ProductsServiceClient is the client API for ProductsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductsServiceClient interface {
	GetProductsByIds(ctx context.Context, in *GetProductsRequest, opts ...grpc.CallOption) (*GetProductsResponse, error)
	UpdateProductQuantityByIds(ctx context.Context, in *UpdateProductQuantityRequest, opts ...grpc.CallOption) (*UpdateProductQuantityResponse, error)
	CreateProduct(ctx context.Context, in *NewProduct, opts ...grpc.CallOption) (*ReturnNewProduct, error)
	CreateCategory(ctx context.Context, in *NewCategory, opts ...grpc.CallOption) (*ReturnNewCategory, error)
	ChangeProduct(ctx context.Context, in *ReturnNewProduct, opts ...grpc.CallOption) (*ReturnNewProduct, error)
	ChangeCategory(ctx context.Context, in *ReturnNewCategory, opts ...grpc.CallOption) (*ReturnNewCategory, error)
	RemoveProduct(ctx context.Context, in *ProductId, opts ...grpc.CallOption) (*RemoveMessage, error)
	RemoveCategory(ctx context.Context, in *CategoryId, opts ...grpc.CallOption) (*RemoveMessage, error)
}

type productsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductsServiceClient(cc grpc.ClientConnInterface) ProductsServiceClient {
	return &productsServiceClient{cc}
}

func (c *productsServiceClient) GetProductsByIds(ctx context.Context, in *GetProductsRequest, opts ...grpc.CallOption) (*GetProductsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProductsResponse)
	err := c.cc.Invoke(ctx, ProductsService_GetProductsByIds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsServiceClient) UpdateProductQuantityByIds(ctx context.Context, in *UpdateProductQuantityRequest, opts ...grpc.CallOption) (*UpdateProductQuantityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateProductQuantityResponse)
	err := c.cc.Invoke(ctx, ProductsService_UpdateProductQuantityByIds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsServiceClient) CreateProduct(ctx context.Context, in *NewProduct, opts ...grpc.CallOption) (*ReturnNewProduct, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReturnNewProduct)
	err := c.cc.Invoke(ctx, ProductsService_CreateProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsServiceClient) CreateCategory(ctx context.Context, in *NewCategory, opts ...grpc.CallOption) (*ReturnNewCategory, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReturnNewCategory)
	err := c.cc.Invoke(ctx, ProductsService_CreateCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsServiceClient) ChangeProduct(ctx context.Context, in *ReturnNewProduct, opts ...grpc.CallOption) (*ReturnNewProduct, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReturnNewProduct)
	err := c.cc.Invoke(ctx, ProductsService_ChangeProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsServiceClient) ChangeCategory(ctx context.Context, in *ReturnNewCategory, opts ...grpc.CallOption) (*ReturnNewCategory, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReturnNewCategory)
	err := c.cc.Invoke(ctx, ProductsService_ChangeCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsServiceClient) RemoveProduct(ctx context.Context, in *ProductId, opts ...grpc.CallOption) (*RemoveMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveMessage)
	err := c.cc.Invoke(ctx, ProductsService_RemoveProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsServiceClient) RemoveCategory(ctx context.Context, in *CategoryId, opts ...grpc.CallOption) (*RemoveMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveMessage)
	err := c.cc.Invoke(ctx, ProductsService_RemoveCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductsServiceServer is the server API for ProductsService service.
// All implementations must embed UnimplementedProductsServiceServer
// for forward compatibility.
type ProductsServiceServer interface {
	GetProductsByIds(context.Context, *GetProductsRequest) (*GetProductsResponse, error)
	UpdateProductQuantityByIds(context.Context, *UpdateProductQuantityRequest) (*UpdateProductQuantityResponse, error)
	CreateProduct(context.Context, *NewProduct) (*ReturnNewProduct, error)
	CreateCategory(context.Context, *NewCategory) (*ReturnNewCategory, error)
	ChangeProduct(context.Context, *ReturnNewProduct) (*ReturnNewProduct, error)
	ChangeCategory(context.Context, *ReturnNewCategory) (*ReturnNewCategory, error)
	RemoveProduct(context.Context, *ProductId) (*RemoveMessage, error)
	RemoveCategory(context.Context, *CategoryId) (*RemoveMessage, error)
	mustEmbedUnimplementedProductsServiceServer()
}

// UnimplementedProductsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProductsServiceServer struct{}

func (UnimplementedProductsServiceServer) GetProductsByIds(context.Context, *GetProductsRequest) (*GetProductsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProductsByIds not implemented")
}
func (UnimplementedProductsServiceServer) UpdateProductQuantityByIds(context.Context, *UpdateProductQuantityRequest) (*UpdateProductQuantityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProductQuantityByIds not implemented")
}
func (UnimplementedProductsServiceServer) CreateProduct(context.Context, *NewProduct) (*ReturnNewProduct, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateProduct not implemented")
}
func (UnimplementedProductsServiceServer) CreateCategory(context.Context, *NewCategory) (*ReturnNewCategory, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCategory not implemented")
}
func (UnimplementedProductsServiceServer) ChangeProduct(context.Context, *ReturnNewProduct) (*ReturnNewProduct, error) {
	return nil, status.Error(codes.Unimplemented, "method ChangeProduct not implemented")
}
func (UnimplementedProductsServiceServer) ChangeCategory(context.Context, *ReturnNewCategory) (*ReturnNewCategory, error) {
	return nil, status.Error(codes.Unimplemented, "method ChangeCategory not implemented")
}
func (UnimplementedProductsServiceServer) RemoveProduct(context.Context, *ProductId) (*RemoveMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveProduct not implemented")
}
func (UnimplementedProductsServiceServer) RemoveCategory(context.Context, *CategoryId) (*RemoveMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveCategory not implemented")
}
func (UnimplementedProductsServiceServer) mustEmbedUnimplementedProductsServiceServer() {}
func (UnimplementedProductsServiceServer) testEmbeddedByValue()                         {}

// UnsafeProductsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductsServiceServer will
// result in compilation errors.
type UnsafeProductsServiceServer interface {
	mustEmbedUnimplementedProductsServiceServer()
}

func RegisterProductsServiceServer(s grpc.ServiceRegistrar, srv ProductsServiceServer) {
	// If the following call panics, it indicates UnimplementedProductsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProductsService_ServiceDesc, srv)
}

func _ProductsService_GetProductsByIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServiceServer).GetProductsByIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductsService_GetProductsByIds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServiceServer).GetProductsByIds(ctx, req.(*GetProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductsService_UpdateProductQuantityByIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProductQuantityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServiceServer).UpdateProductQuantityByIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductsService_UpdateProductQuantityByIds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServiceServer).UpdateProductQuantityByIds(ctx, req.(*UpdateProductQuantityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductsService_CreateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewProduct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServiceServer).CreateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductsService_CreateProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServiceServer).CreateProduct(ctx, req.(*NewProduct))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductsService_CreateCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewCategory)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServiceServer).CreateCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductsService_CreateCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServiceServer).CreateCategory(ctx, req.(*NewCategory))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductsService_ChangeProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReturnNewProduct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServiceServer).ChangeProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductsService_ChangeProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServiceServer).ChangeProduct(ctx, req.(*ReturnNewProduct))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductsService_ChangeCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReturnNewCategory)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServiceServer).ChangeCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductsService_ChangeCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServiceServer).ChangeCategory(ctx, req.(*ReturnNewCategory))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductsService_RemoveProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServiceServer).RemoveProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductsService_RemoveProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServiceServer).RemoveProduct(ctx, req.(*ProductId))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductsService_RemoveCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CategoryId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServiceServer).RemoveCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductsService_RemoveCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServiceServer).RemoveCategory(ctx, req.(*CategoryId))
	}
	return interceptor(ctx, in, info, handler)
}

// ProductsService_ServiceDesc is the grpc.ServiceDesc for ProductsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "products.ProductsService",
	HandlerType: (*ProductsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProductsByIds",
			Handler:    _ProductsService_GetProductsByIds_Handler,
		},
		{
			MethodName: "UpdateProductQuantityByIds",
			Handler:    _ProductsService_UpdateProductQuantityByIds_Handler,
		},
		{
			MethodName: "CreateProduct",
			Handler:    _ProductsService_CreateProduct_Handler,
		},
		{
			MethodName: "CreateCategory",
			Handler:    _ProductsService_CreateCategory_Handler,
		},
		{
			MethodName: "ChangeProduct",
			Handler:    _ProductsService_ChangeProduct_Handler,
		},
		{
			MethodName: "ChangeCategory",
			Handler:    _ProductsService_ChangeCategory_Handler,
		},
		{
			MethodName: "RemoveProduct",
			Handler:    _ProductsService_RemoveProduct_Handler,
		},
		{
			MethodName: "RemoveCategory",
			Handler:    _ProductsService_RemoveCategory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "product.proto",
}
